cols: 80
rows: 15
frameDelay: 120
repeat: 0
quality: 100
theme:
  background: "#2E86C1"
  foreground: "#ffffff"
  cursor: "#ffffff"
cursorStyle: block
commands:
  - command: "bash scripts/terminal_demo.sh"
    delay: 500
