#!/bin/bash
set -e

USERNAME=${USERNAME:-"𖢧ꛅ𖤢ꚽꚳꛈ𖢧ꛕꛅ"}
CURRENT_TIME=${CURRENT_TIME:-$(date -u +"%Y-%m-%d %T")}

# Generate random load average
generate_load_avg() {
  printf "%.2f %.2f %.2f" \
    "$(echo "scale=2; ${RANDOM}/32767 + 0.1" | bc)" \
    "$(echo "scale=2; ${RANDOM}/32767 + 0.2" | bc)" \
    "$(echo "scale=2; ${RANDOM}/32767 + 0.1" | bc)"
}

# Generate terminal output
generate_terminal_content() {
  local LOAD_AVG=$(generate_load_avg)
  mkdir -p dist
  cat > terminal_output.txt << EOF
Last login: ${CURRENT_TIME} on ttys000
${USERNAME}@github ~ % uptime
${CURRENT_TIME} up 02:51, 1 user, load average: ${LOAD_AVG}

${USERNAME}@github ~ % ls -la Projects/
drwxr-xr-x  8 ${USERNAME}  staff  256 May 07 02:51 .
-rw-r--r--  1 ${USERNAME}  staff  925 May 07 02:51 TODO.md

${USERNAME}@github ~ % cat Projects/TODO.md
# ℭ𝔲𝔯𝔯𝔢𝔫𝔱 𝔓𝔯𝔬𝔧𝔢𝔠𝔱𝔰 📋
→ Automating deployment workflows
→ Contributing to open source
→ Learning Kubernetes
→ Building shell script utilities
EOF
}

# Generate README
generate_readme() {
  cat > README.md << EOF
<div align="center">
  <img src="dist/header.svg" alt="Header Glyphs" width="100%" />
</div>

<pre class="terminal">
$(cat terminal_output.txt)
</pre>

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="dist/github-snake-dark.svg?ts=${CURRENT_TIME//:/%3A}" />
  <source media="(prefers-color-scheme: light)" srcset="dist/github-snake.svg?ts=${CURRENT_TIME//:/%3A}" />
  <img alt="Github Contribution Snake Animation" src="dist/github-snake.svg?ts=${CURRENT_TIME//:/%3A}" />
</picture>

<div align="center">
  <img src="dist/quote.svg" alt="Terminal quote" />
</div>

<sub align="center">🧿 Last Updated: ${CURRENT_TIME} UTC • Auto-generated by update_readme.sh</sub>
EOF
}

# Main execution
main() {
  node scripts/generate-header.js
  node scripts/generate-terminal-svg.js
  generate_terminal_content
  generate_readme
  rm -f terminal_output.txt
}

main