name: Q.R.L.P Neon Snake Update

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-neon-snake:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2️⃣ Ensure dist folder exists
      - name: Create dist Directory
        run: mkdir -p dist

      # 3️⃣ Generate Neon Contribution Snake
      - name: Generate Neon Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          color_snake: '#39FF14'      # Neon green main snake
          color_dots: '#00FFF0'       # Neon cyan contribution dots
          color_background: '#0d0d0d' # Dark background for snake

      # 4️⃣ Commit & push updates
      - name: Commit & Push Snake Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "Thugger069"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f dist/github-snake*.svg
          git commit -m "🧬 Q.R.L.P Neon Snake Update ($(date +'%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
          git push