name: Update Snake
on:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday
  workflow_dispatch:

jobs:
  render-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libnss3 libxss1 libgbm-dev libxshmfence-dev gifsicle nsnake
          pip install snake

      - name: Install Terminalizer
        run: |
          npm install -g terminalizer

      - name: Record Snake Game
        run: |
          # Check if snake-config.yml exists
          if [ -f ./snake-config.yml ]; then
            terminalizer record snake-session --config ./snake-config.yml -k "nsnake"
          else
            echo "snake-config.yml not found. Skipping recording."
          fi

      - name: Fix Sandbox Permissions
        run: |
          # Check if chrome-sandbox binary exists
          if [ -f /usr/local/lib/node_modules/terminalizer/node_modules/electron/dist/chrome-sandbox ]; then
            sudo chmod 4755 /usr/local/lib/node_modules/terminalizer/node_modules/electron/dist/chrome-sandbox
          else
            echo "chrome-sandbox binary not found. Skipping permission fix."
          fi

      - name: Start Xvfb and Render
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          # Disable Electron sandboxing (if permissions fail)
          export ELECTRON_DISABLE_SANDBOX=1
          terminalizer render snake-config.yml --output docs/snake.gif

      - name: Optimize GIF
        run: |
          gifsicle --optimize=3 --lossy=50 docs/snake.gif -o docs/snake.gif

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "Thugger069@noreply.github.com"
          git add docs/snake.gif
          git commit -m "Update snake" || echo "No changes to commit"
          git push
