name: Automated Snake Demo
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  generate-snake-gif:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ELECTRON_DISABLE_SANDBOX: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ''

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            x11-utils \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libgbm-dev \
            libxshmfence-dev \
            gifsicle \
            nsnake

      - name: Install Terminalizer
        run: npm install -g terminalizer@0.7.2 --no-package-lock

      - name: Start Xvfb Server
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          echo "DISPLAY=${DISPLAY}" >> $GITHUB_ENV

      - name: Create Configuration
        run: |
          chmod +x ./scripts/snake-config.sh
          ./scripts/snake-config.sh

      - name: Verify Environment
        run: |
          echo "Current DISPLAY: $DISPLAY"
          xdpyinfo -display :99 > /dev/null
          echo "Xvfb verification successful"

      - name: Record Gameplay
        run: |
          terminalizer record snake-session \
            --config ./snake-config.yml \
            --command nsnake \
            --skip-sharing

      - name: Render GIF
        run: |
          terminalizer render snake-session \
            --output docs/snake.gif \
            --no-sandbox

      - name: Optimize GIF
        run: |
          gifsicle --optimize=3 --lossy=50 docs/snake.gif -o optimized.gif
          mv optimized.gif docs/snake.gif

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "Thugger069@noreply.github.com"
          git add docs/snake.gif
          git diff-index --quiet HEAD || (git commit -m "Update snake demo" && git push)