name: Snake Overlord
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Create dist directory
        run: mkdir -p dist
      - name: Generate the Snake
        uses: Platane/snk@master
        with:
          github_user_name: '${{ github.repository_owner }}'
          svg_out_path: dist/github-snake.svg
          color_snake: '#ff0000'
          color_dots: '#00ff00'
      - name: Force-Spawn the Snake
        run: >
          sed -i '/<!-- START SNAKE -->/,/<!-- END SNAKE -->/c\<!-- START SNAKE
          -->\n![Snake](dist/github-snake.svg?ts=${{ github.run_id }})\n<!-- END
          SNAKE -->' README.md
      - name: Commit the Chaos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Thugger069"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snake: $(date +'%Y-%m-%d')"
          git push
