name: Snake Overlord
'on':
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Generate the Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          color_snake: '#ff0000'
          color_dots: '#00ff00'
          
      - name: Update README with Snake
        run: |
          # Create a backup of the README
          cp README.md README.md.bak
          
          # Update the snake animation section
          sed -i '/<!-- START SNAKE -->/,/<!-- END SNAKE -->/c\<!-- START SNAKE -->\n<picture>\n  <source media="(prefers-color-scheme: dark)" srcset="dist/github-snake-dark.svg?ts=${{ github.run_id }}" />\n  <source media="(prefers-color-scheme: light)" srcset="dist/github-snake.svg?ts=${{ github.run_id }}" />\n  <img alt="Github Contribution Snake Animation" src="dist/github-snake.svg?ts=${{ github.run_id }}" />\n</picture>\n<!-- END SNAKE -->' README.md
          
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake*.svg README.md
          git commit -m "🐍 Update contribution snake animation ($(date +'%Y-%m-%d'))"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
