name: Update Terminal GIF

on:
  schedule:
    - cron: '0 0 * * *'  # Daily update
  workflow_dispatch:

jobs:
  generate-terminal-gif:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get install -y \
          ffmpeg \
          screen \
          ttyrec \
          gifsicle
        sudo apt install npm -y
        sudo npm install -g ttygif

    - name: Generate Terminal Animation
      run: |
        echo "${{ secrets.TERMINAL_MESSAGE }}" | ttyrec

    - name: Convert to GIF
      run: |
        ttygif -i ttyrecord -o terminal.gif

    - name: Commit and Push GIF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Thugger069"
        git config --global user.email "Thugger069@noreply.github.com"
        git add terminal.gif
        git commit -m "Update terminal GIF"
        git push

