name: Terminal Animation
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-terminal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb lolcat figlet neofetch fonts-firacode
          
      - name: Install dependencies
        run: |
          npm install -g terminalizer@0.8.2
          pip install lolcat==1.4
          
      - name: Record terminal session
        run: |
          chmod +x scripts/terminal_demo.sh
          xvfb-run terminalizer record -k -c config/terminalizer.yml
          terminalizer render terminalizer-config.yml -o assets/terminal.gif
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/terminal.gif
          git commit -m "🔄 Update terminal animation"
          git push
