name: CyberTerminal Animator

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon UTC
  workflow_dispatch:

jobs:
  generate-terminal:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            imagemagick \
            figlet \
            lolcat \
            neofetch \
            fonts-firacode \
            libgtk-3-0 \
            libnotify4 \
            libnss3 \
            libxss1 \
            libxtst6

      - name: Install Dependencies
        run: |
          npm install -g terminalizer@0.8.2
          pip install lolcat==1.4

      - name: Verify Font Configuration
        run: |
          fc-cache -f -v
          fc-list | grep "Fira Code"

      - name: Record Terminal Session
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            chmod +x scripts/terminal_demo.sh
            terminalizer record config/terminalizer.yml \
              --command "./scripts/terminal_demo.sh" \
              --output recording.json

      - name: Render GIF Animation
        run: |
          terminalizer render recording.json \
            --output terminal-raw.gif \
            --config config/terminalizer.yml
          
          gifsicle --optimize=3 --colors 128 \
            --output assets/terminal.gif \
            terminal-raw.gif

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/terminal.gif
          git commit -m "🔄 Automated terminal animation update"
          git push
