name: Generate Terminal GIF

on:
  push:
    branches:
      - main

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y asciinema ffmpeg

      - name: Record terminal session
        run: |
          echo 'echo "Hi there! I am Thugger069!" && sleep 2' > script.sh
          chmod +x script.sh
          asciinema rec --quiet -c ./script.sh terminal.cast
          asciicast2gif -s 2 -t solarized-dark terminal.cast ./assets/terminal.gif

      - name: Commit GIF to repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add assets/terminal.gif
          git commit -m "Updated terminal GIF"
          git push
