name: CyberTerminal Animator

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon UTC
  workflow_dispatch:

jobs:
  generate-terminal:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
	
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            imagemagick \
            figlet \
            lolcat \
            neofetch \
            fonts-firacode \
 
     - name: Install Docker
       run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
         sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    # Install Docker components
         sudo apt-get update
         sudo apt-get install -y \
             docker-ce \
             docker-ce-cli \
             containerd.io \
             docker-buildx-plugin \
             docker-compose-plugin
    
          sudo docker run hello-world

      - name: Install Dependencies
        run: |
          npm install -g terminalizer@0.7.2
          pip install lolcat

      - name: Verify Config Files
        run: |
          ls -la config/
          ls -la scripts/

      - name: Run Terminal Recording
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            terminalizer record config/terminalizer.yml -k \
              --command "bash scripts/terminal_demo.sh" \
              --output terminal-raw.gif
            
            # Optimize GIF
            gifsicle --optimize=3 --colors 128 -o assets/terminal.gif terminal-raw.gif

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/terminal.gif
          git commit -m "🔄 Automated terminal animation update"
          git push
