name: Generate Welcome GIF

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/welcome-gif.yml'
      - 'config/welcome-config.yml'
  workflow_dispatch:

jobs:
  create-gif:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            figlet \
            lolcat \
            neofetch \
            boxes \
            cowsay \
            fortune \
            bc
          npm install -g terminalizer
          
      - name: Create welcome message configuration
        run: |
          mkdir -p config
          cat > config/welcome-config.yml << EOF
          # Terminalizer Configuration
          config:
            command: bash
            cwd: /home/runner
            env:
              recording: true
            cols: 100
            rows: 30
            repeat: 0
            quality: 100
            frameDelay: 50
            maxIdleTime: 2000
            frameBox:
              type: solid
              title: null
              style:
                boxShadow: none
                margin: 0px
            fontSize: 14
            fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
            theme:
              background: "#1a1b26"
              foreground: "#a9b1d6"
              cursor: "#f7768e"
              black: "#32344a"
              red: "#f7768e"
              green: "#9ece6a"
              yellow: "#e0af68"
              blue: "#7aa2f7"
              magenta: "#ad8ee6"
              cyan: "#449dab"
              white: "#787c99"
              brightBlack: "#444b6a"
              brightRed: "#ff7a93"
              brightGreen: "#b9f27c"
              brightYellow: "#ff9e64"
              brightBlue: "#7da6ff"
              brightMagenta: "#bb9af7"
              brightCyan: "#0db9d7"
              brightWhite: "#acb0d0"
          
          records:
            - delay: 1000
              content: "\u001b[?25l\u001b[2J\u001b[1;1H"
            - delay: 500
              content: "$ "
            - delay: 200
              content: "e"
            - delay: 100
              content: "c"
            - delay: 100
              content: "h"
            - delay: 100
              content: "o"
            - delay: 100
              content: " "
            - delay: 100
              content: "'"
            - delay: 300
              content: "Hi there! I'm Thugger069."
            - delay: 1000
              content: "\n$ "
            - delay: 200
              content: "echo 'I'm passionate about coding and technology.'"
            - delay: 1000
              content: "\n$ "
            - delay: 200
              content: "echo 'Welcome to my profile!'"
            - delay: 1000
              content: "\n$ "
            - delay: 200
              content: "neofetch"
            - delay: 500
              content: "\n"
          EOF
          
      - name: Generate Welcome GIF
        run: |
          terminalizer render config/welcome-config.yml -o assets/welcome.gif
          
      - name: Optimize GIF
        run: |
          sudo apt-get install -y gifsicle
          gifsicle -O3 assets/welcome.gif -o assets/welcome.gif
          
      - name: Commit and Push
        run: |
          git config --global user.name "Thugger069"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/welcome.gif
          git diff --quiet && git diff --staged --quiet || (git commit -m "🎬 Update welcome GIF" && git push)
